import { addDaysISO, nowISO } from "@/lib/dates"
import type { Activity, NimbusStore, Person, Project } from "@/lib/types"

const created = nowISO()

const people: Person[] = [
  { id: "ppl-andrea", name: "Andrea Rossi" },
  { id: "ppl-laura", name: "Laura Conti" },
  { id: "ppl-netops", name: "NetOps" },
  { id: "ppl-sara", name: "Sara Greco" },
  { id: "ppl-team-azure", name: "team Azure" },
  { id: "ppl-referente", name: "Referente cliente" },
  { id: "ppl-helpdesk", name: "Helpdesk interno" },
  { id: "ppl-iam", name: "team IAM" },
  { id: "ppl-paolo", name: "Paolo Mancini" },
  { id: "ppl-giulia", name: "Giulia Ferri" },
  { id: "ppl-cloudwatch", name: "Monitoraggio CloudWatch" },
  { id: "ppl-marco", name: "Marco Bianchi" },
  { id: "ppl-referente-it", name: "Referente IT cliente" },
  { id: "ppl-tu", name: "Tu" },
]

const projects: Project[] = [
  {
    id: "prj-tributi",
    name: "Cloud AWS · Piattaforma Tributi",
    client: "Maggioli — Area Enti Locali",
    status: "attivo",
    driveUrl: "https://drive.google.com/drive/folders/tributi-cloud",
    personIds: ["ppl-andrea", "ppl-laura", "ppl-netops", "ppl-marco"],
    categories: [
      { id: "cat-tributi-app", name: "Applicativo" },
      { id: "cat-tributi-infra", name: "Infrastruttura" },
      { id: "cat-tributi-doc", name: "Documentazione" },
    ],
    notes:
      "Ambienti prod/QA su AWS. Priorità: certificati, peering VPC e finestre di manutenzione concordate con il cliente.",
    createdAt: created,
    updatedAt: created,
  },
  {
    id: "prj-azure-comuni",
    name: "Migrazione Azure · Comuni",
    client: "Maggioli — Cloud Practice",
    status: "attivo",
    driveUrl: "https://drive.google.com/drive/folders/migrazione-azure-comuni",
    personIds: ["ppl-sara", "ppl-team-azure", "ppl-referente", "ppl-referente-it"],
    categories: [
      { id: "cat-azure-app", name: "Applicativo" },
      { id: "cat-azure-infra", name: "Infrastruttura" },
      { id: "cat-azure-doc", name: "Documentazione" },
    ],
    notes:
      "Lift-and-shift di tre comuni pilota. Kick-off già fatto; manca la finestra AD e il piano RDS.",
    createdAt: created,
    updatedAt: created,
  },
  {
    id: "prj-qa",
    name: "Supporto ambienti QA",
    client: "Maggioli — Internal IT",
    status: "in_attesa",
    driveUrl: "https://drive.google.com/drive/folders/ambienti-qa",
    personIds: ["ppl-helpdesk", "ppl-iam"],
    categories: [
      { id: "cat-qa-app", name: "Applicativo" },
      { id: "cat-qa-infra", name: "Infrastruttura" },
    ],
    notes:
      "Richieste spot di accessi e collaudi. Tenerle in inbox e smistarle senza aprire un nuovo progetto ogni volta.",
    createdAt: created,
    updatedAt: created,
  },
]

const activities: Activity[] = [
  {
    id: "act-inbox-rimini",
    title: "Nuovo ambiente di collaudo per il Comune di Rimini",
    description:
      "Email del commerciale: serve un ambiente QA isolato entro la prossima sprint. Verificare se rientra in Tributi o in un progetto a parte.",
    projectId: null,
    source: "email",
    requesterId: "ppl-paolo",
    type: "eseguo",
    status: "inbox",
    priority: "alta",
    dueDate: null,
    assigneeIds: [],
    waitingOnPersonId: null,
    waitingReason: "",
    driveUrl: "",
    categoryId: null,
    createdAt: created,
    updatedAt: created,
  },
  {
    id: "act-inbox-iam",
    title: "Accessi IAM al bucket backup-dev",
    description:
      "Messaggio Teams: tre sviluppatori non vedono gli oggetti del bucket. Probabile policy errata sul ruolo di QA.",
    projectId: "prj-qa",
    source: "chat",
    requesterId: "ppl-giulia",
    type: "eseguo",
    status: "inbox",
    priority: "media",
    dueDate: null,
    assigneeIds: [],
    waitingOnPersonId: null,
    waitingReason: "",
    driveUrl: "",
    categoryId: "cat-qa-infra",
    createdAt: created,
    updatedAt: created,
  },
  {
    id: "act-overdue-tls",
    title: "Rinnovo certificato TLS sul load balancer di produzione",
    description:
      "Scadenza ACM già superata nel calendario. Coordinare il cut-over con il funzionale e aggiornare la cartella Drive dei certificati.",
    projectId: "prj-tributi",
    source: "altro",
    requesterId: "ppl-cloudwatch",
    type: "eseguo",
    status: "in_corso",
    priority: "alta",
    dueDate: addDaysISO(-2),
    assigneeIds: [],
    waitingOnPersonId: null,
    waitingReason: "",
    driveUrl: "https://drive.google.com/drive/folders/tributi-certificati",
    categoryId: "cat-tributi-infra",
    createdAt: created,
    updatedAt: created,
  },
  {
    id: "act-today-peering",
    title: "Allineamento team rete sul peering VPC di QA",
    description:
      "Serve conferma CIDR e route table prima di aprire il ticket AWS. Tu coordini, non esegui il change.",
    projectId: "prj-tributi",
    source: "chat",
    requesterId: "ppl-laura",
    type: "coordino",
    status: "in_corso",
    priority: "alta",
    dueDate: addDaysISO(0),
    assigneeIds: ["ppl-netops"],
    waitingOnPersonId: "ppl-netops",
    waitingReason: "Manca il CIDR definitivo del VPC QA",
    driveUrl: "",
    categoryId: "cat-tributi-infra",
    createdAt: created,
    updatedAt: created,
  },
  {
    id: "act-rds",
    title: "Stima effort migrazione RDS PostgreSQL 16",
    description:
      "Preparare una stima per il steering committee: downtime, replica, rollback. Documento da lasciare in Drive.",
    projectId: "prj-azure-comuni",
    source: "email",
    requesterId: "ppl-sara",
    type: "eseguo",
    status: "in_corso",
    priority: "media",
    dueDate: addDaysISO(2),
    assigneeIds: [],
    waitingOnPersonId: null,
    waitingReason: "",
    driveUrl: "",
    categoryId: "cat-azure-app",
    createdAt: created,
    updatedAt: created,
  },
  {
    id: "act-wait-firewall",
    title: "Apertura firewall verso SFTP Maggioli",
    description:
      "I collaudi del Comune pilota sono bloccati. Sollecitare NetOps se non arriva risposta oggi.",
    projectId: "prj-tributi",
    source: "email",
    requesterId: "ppl-andrea",
    type: "coordino",
    status: "in_attesa",
    priority: "alta",
    dueDate: addDaysISO(-1),
    assigneeIds: ["ppl-marco"],
    waitingOnPersonId: "ppl-marco",
    waitingReason: "Change firewall in coda CAB",
    driveUrl: "",
    categoryId: "cat-tributi-infra",
    createdAt: created,
    updatedAt: created,
  },
  {
    id: "act-wait-ad",
    title: "Conferma finestra di manutenzione Azure AD",
    description:
      "Senza la finestra del cliente non si parte con i tre comuni pilota.",
    projectId: "prj-azure-comuni",
    source: "email",
    requesterId: "ppl-referente",
    type: "coordino",
    status: "in_attesa",
    priority: "media",
    dueDate: addDaysISO(1),
    assigneeIds: ["ppl-referente-it"],
    waitingOnPersonId: "ppl-referente-it",
    waitingReason: "Attesa conferma calendario interno",
    driveUrl: "",
    categoryId: "cat-azure-infra",
    createdAt: created,
    updatedAt: created,
  },
  {
    id: "act-kickoff",
    title: "Redigere verbale kick-off migrazione Azure",
    description:
      "Trascrivere decisioni, rischi e prossimi passi. Caricare il verbale in Drive e spedirlo ai presenti.",
    projectId: "prj-azure-comuni",
    source: "altro",
    requesterId: "ppl-tu",
    type: "eseguo",
    status: "in_corso",
    priority: "bassa",
    dueDate: addDaysISO(1),
    assigneeIds: [],
    waitingOnPersonId: null,
    waitingReason: "",
    driveUrl: "https://drive.google.com/drive/folders/migrazione-azure-comuni",
    categoryId: "cat-azure-doc",
    createdAt: created,
    updatedAt: created,
  },
  {
    id: "act-done-eip",
    title: "Ticket AWS Support per quota Elastic IP",
    description: "Quota alzata. Ticket chiuso, nota lasciata in Drive.",
    projectId: "prj-tributi",
    source: "altro",
    requesterId: "ppl-tu",
    type: "eseguo",
    status: "fatto",
    priority: "media",
    dueDate: addDaysISO(-5),
    assigneeIds: [],
    waitingOnPersonId: null,
    waitingReason: "",
    driveUrl: "",
    categoryId: "cat-tributi-infra",
    createdAt: created,
    updatedAt: created,
  },
]

export const SEED_STORE: NimbusStore = {
  version: 3,
  people,
  projects,
  activities,
}
