import { addDaysISO, nowISO } from "@/lib/dates"
import { dateToNoonStartsAt } from "@/lib/tasks"
import type {
  Activity,
  NimbusStore,
  Person,
  PersonKind,
  Project,
  Task,
} from "@/lib/types"

const created = nowISO()

function person(
  id: string,
  name: string,
  kind: PersonKind = "persona",
  memberIds: string[] = [],
): Person {
  return { id, name, kind, memberIds, archivedAt: null }
}

const people: Person[] = [
  person("ppl-andrea", "Andrea Rossi"),
  person("ppl-laura", "Laura Conti"),
  person("ppl-netops", "NetOps", "team"),
  person("ppl-sara", "Sara Greco"),
  person("ppl-team-azure", "team Azure", "team"),
  person("ppl-referente", "Referente cliente"),
  person("ppl-helpdesk", "Helpdesk interno", "team"),
  person("ppl-iam", "team IAM", "team"),
  person("ppl-paolo", "Paolo Mancini"),
  person("ppl-giulia", "Giulia Ferri"),
  person("ppl-cloudwatch", "Monitoraggio CloudWatch", "team"),
  person("ppl-marco", "Marco Bianchi"),
  person("ppl-luca", "Luca Neri"),
  person("ppl-referente-it", "Referente IT cliente"),
  person("ppl-tu", "Pier Luigi Laviano"),
]

const projects: Project[] = [
  {
    id: "prj-tributi",
    name: "Cloud AWS · Piattaforma Tributi",
    client: "Azienda — Area Enti Locali",
    status: "attivo",
    color: "teal",
    driveUrl: "https://drive.google.com/drive/folders/tributi-cloud",
    managerId: "ppl-tu",
    participantIds: [
      "ppl-andrea",
      "ppl-laura",
      "ppl-netops",
      "ppl-marco",
      "ppl-luca",
    ],
    categories: [
      { id: "cat-tributi-app", name: "Applicativo" },
      { id: "cat-tributi-infra", name: "Infrastruttura" },
      { id: "cat-tributi-doc", name: "Documentazione" },
    ],
    notes:
      "Ambienti prod/QA su AWS. Priorità: certificati, peering VPC e finestre di manutenzione concordate con il cliente.",
    createdAt: created,
    updatedAt: created,
  },
  {
    id: "prj-azure-comuni",
    name: "Migrazione Azure · Comuni",
    client: "Azienda — Cloud Practice",
    status: "attivo",
    color: "amber",
    driveUrl: "https://drive.google.com/drive/folders/migrazione-azure-comuni",
    managerId: "ppl-sara",
    participantIds: [
      "ppl-sara",
      "ppl-team-azure",
      "ppl-referente",
      "ppl-referente-it",
    ],
    categories: [
      { id: "cat-azure-app", name: "Applicativo" },
      { id: "cat-azure-infra", name: "Infrastruttura" },
      { id: "cat-azure-doc", name: "Documentazione" },
    ],
    notes:
      "Lift-and-shift di tre comuni pilota. Kick-off già fatto; manca la finestra AD e il piano RDS.",
    createdAt: created,
    updatedAt: created,
  },
  {
    id: "prj-qa",
    name: "Supporto ambienti QA",
    client: "Azienda — Internal IT",
    status: "in_attesa",
    color: "sky",
    driveUrl: "https://drive.google.com/drive/folders/ambienti-qa",
    managerId: "ppl-tu",
    participantIds: ["ppl-helpdesk", "ppl-iam"],
    categories: [
      { id: "cat-qa-app", name: "Applicativo" },
      { id: "cat-qa-infra", name: "Infrastruttura" },
    ],
    notes:
      "Richieste spot di accessi e collaudi. Tenerle da pianificare senza aprire un nuovo progetto ogni volta.",
    createdAt: created,
    updatedAt: created,
  },
]

type SeedActivity = Omit<Activity, "responsibleId" | "participantIds" | "reminderOn"> &
  Partial<Pick<Activity, "responsibleId" | "participantIds" | "reminderOn">>

function completeActivity(activity: SeedActivity): Activity {
  return {
    ...activity,
    responsibleId: activity.responsibleId ?? "ppl-tu",
    participantIds: activity.participantIds ?? [],
    reminderOn: activity.reminderOn ?? null,
  }
}

const activities: SeedActivity[] = [
  {
    id: "act-plan-rimini",
    title: "Nuovo ambiente di collaudo per il Comune di Rimini",
    description:
      "Serve un ambiente QA isolato entro la prossima sprint. Verificare se rientra in Tributi o in un progetto a parte.",
    projectId: null,
    source: "altro",
    requesterId: "ppl-paolo",
    responsibleId: "ppl-tu",
    participantIds: ["ppl-sara"],
    reminderOn: addDaysISO(10),
    status: "in_attesa",
    priority: "alta",
    waitingOnPersonId: null,
    waitingReason: "",
    closingNote: "",
    attachments: [],
    driveUrl: "",
    categoryId: null,
    createdAt: created,
    updatedAt: created,
  },
  {
    id: "act-plan-iam",
    title: "Accessi IAM al bucket backup-dev",
    description:
      "Tre sviluppatori non vedono gli oggetti del bucket. Probabile policy errata sul ruolo di QA.",
    projectId: "prj-qa",
    source: "altro",
    requesterId: "ppl-giulia",
    responsibleId: "ppl-tu",
    status: "in_attesa",
    priority: "media",
    waitingOnPersonId: null,
    waitingReason: "",
    closingNote: "",
    attachments: [],
    driveUrl: "",
    categoryId: "cat-qa-infra",
    createdAt: created,
    updatedAt: created,
  },
  {
    id: "act-overdue-tls",
    title: "Rinnovo certificato TLS sul load balancer di produzione",
    description:
      "Scadenza ACM già superata nel calendario. Coordinare il cut-over con il funzionale e aggiornare la cartella Drive dei certificati.",
    projectId: "prj-tributi",
    source: "altro",
    requesterId: "ppl-cloudwatch",
    responsibleId: "ppl-tu",
    status: "in_corso",
    priority: "alta",
    waitingOnPersonId: null,
    waitingReason: "",
    closingNote: "",
    attachments: [],
    driveUrl: "https://drive.google.com/drive/folders/tributi-certificati",
    categoryId: "cat-tributi-infra",
    createdAt: created,
    updatedAt: created,
  },
  {
    id: "act-today-peering",
    title: "Allineamento team rete sul peering VPC di QA",
    description:
      "NetOps è responsabile del risultato. Mario e Luca eseguono il change; Pier resta coinvolto per il coordinamento con il cliente.",
    projectId: "prj-tributi",
    source: "chat",
    requesterId: "ppl-laura",
    responsibleId: "ppl-netops",
    participantIds: ["ppl-tu"],
    status: "in_corso",
    priority: "alta",
    waitingOnPersonId: null,
    waitingReason: "",
    closingNote: "",
    attachments: [],
    driveUrl: "",
    categoryId: "cat-tributi-infra",
    createdAt: created,
    updatedAt: created,
  },
  {
    id: "act-rds",
    title: "Stima effort migrazione RDS PostgreSQL 16",
    description:
      "Pier è responsabile. Marco esegue la stima e resta coinvolto nel confronto con il cliente.",
    projectId: "prj-azure-comuni",
    source: "email",
    requesterId: "ppl-referente",
    responsibleId: "ppl-tu",
    participantIds: ["ppl-marco"],
    status: "in_corso",
    priority: "media",
    waitingOnPersonId: null,
    waitingReason: "",
    closingNote: "",
    attachments: [],
    driveUrl: "",
    categoryId: "cat-azure-app",
    createdAt: created,
    updatedAt: created,
  },
  {
    id: "act-wait-firewall",
    title: "Apertura firewall verso SFTP Azienda",
    description:
      "I collaudi del Comune pilota sono bloccati. Sollecitare NetOps se non arriva risposta oggi.",
    projectId: "prj-tributi",
    source: "email",
    requesterId: "ppl-andrea",
    responsibleId: "ppl-tu",
    status: "in_attesa",
    priority: "alta",
    waitingOnPersonId: "ppl-marco",
    waitingReason: "Change firewall in coda CAB",
    closingNote: "",
    attachments: [],
    driveUrl: "",
    categoryId: "cat-tributi-infra",
    createdAt: created,
    updatedAt: created,
  },
  {
    id: "act-wait-ad",
    title: "Conferma finestra di manutenzione Azure AD",
    description:
      "Senza la finestra del cliente non si parte con i tre comuni pilota.",
    projectId: "prj-azure-comuni",
    source: "email",
    requesterId: "ppl-referente",
    responsibleId: "ppl-sara",
    status: "in_attesa",
    priority: "media",
    waitingOnPersonId: "ppl-referente-it",
    waitingReason: "Attesa conferma calendario interno",
    closingNote: "",
    attachments: [],
    driveUrl: "",
    categoryId: "cat-azure-infra",
    createdAt: created,
    updatedAt: created,
  },
  {
    id: "act-kickoff",
    title: "Redigere verbale kick-off migrazione Azure",
    description:
      "Trascrivere decisioni, rischi e prossimi passi. Caricare il verbale in Drive e spedirlo ai presenti.",
    projectId: "prj-azure-comuni",
    source: "altro",
    requesterId: "ppl-tu",
    responsibleId: "ppl-tu",
    status: "in_corso",
    priority: "bassa",
    waitingOnPersonId: null,
    waitingReason: "",
    closingNote: "",
    attachments: [],
    driveUrl: "https://drive.google.com/drive/folders/migrazione-azure-comuni",
    categoryId: "cat-azure-doc",
    createdAt: created,
    updatedAt: created,
  },
  {
    id: "act-done-eip",
    title: "Ticket AWS Support per quota Elastic IP",
    description: "Quota alzata. Ticket chiuso, nota lasciata in Drive.",
    projectId: "prj-tributi",
    source: "altro",
    requesterId: "ppl-tu",
    responsibleId: "ppl-tu",
    status: "fatto",
    priority: "media",
    waitingOnPersonId: null,
    waitingReason: "",
    closingNote: "Quota alzata. Ticket chiuso, nota lasciata in Drive.",
    attachments: [],
    driveUrl: "",
    categoryId: "cat-tributi-infra",
    createdAt: created,
    updatedAt: created,
  },
]

const tasks: Task[] = [
  {
    id: "tsk-tls",
    activityId: "act-overdue-tls",
    startsAt: dateToNoonStartsAt(addDaysISO(-2)),
    endsAt: null,
    executorIds: ["ppl-tu"],
    notes: "",
  },
  {
    id: "tsk-peering",
    activityId: "act-today-peering",
    startsAt: `${addDaysISO(0)}T15:00`,
    endsAt: `${addDaysISO(0)}T16:00`,
    executorIds: ["ppl-marco", "ppl-luca"],
    notes: "Allineamento su CIDR e route table",
  },
  {
    id: "tsk-rds",
    activityId: "act-rds",
    startsAt: dateToNoonStartsAt(addDaysISO(2)),
    endsAt: null,
    executorIds: ["ppl-marco"],
    notes: "",
  },
  {
    id: "tsk-firewall",
    activityId: "act-wait-firewall",
    startsAt: dateToNoonStartsAt(addDaysISO(-1)),
    endsAt: null,
    executorIds: ["ppl-marco"],
    notes: "",
  },
  {
    id: "tsk-ad",
    activityId: "act-wait-ad",
    startsAt: dateToNoonStartsAt(addDaysISO(1)),
    endsAt: null,
    executorIds: ["ppl-referente-it"],
    notes: "",
  },
  {
    id: "tsk-kickoff",
    activityId: "act-kickoff",
    startsAt: dateToNoonStartsAt(addDaysISO(1)),
    endsAt: null,
    executorIds: ["ppl-tu"],
    notes: "",
  },
  {
    id: "tsk-eip",
    activityId: "act-done-eip",
    startsAt: `${addDaysISO(-5)}T09:30`,
    endsAt: `${addDaysISO(-5)}T10:00`,
    executorIds: ["ppl-tu"],
    notes: "",
  },
]

type Execution = {
  id: string
  projectId: string
  categoryId: string | null
  title: string
  description: string
  outcome: "fatto" | "fallita"
  closingNote: string
  daysAgo: number
  start: string
  end: string | null
  executorIds?: string[]
  slotNote?: string
  requesterId?: string | null
  responsibleId?: string | null
}

const executions: Execution[] = [
  {
    id: "kms",
    projectId: "prj-tributi",
    categoryId: "cat-tributi-infra",
    title: "Rotazione chiavi KMS ambiente prod",
    description: "Rotazione annuale delle CMK usate da RDS e S3.",
    outcome: "fatto",
    closingNote: "Chiavi ruotate, alias aggiornati. Nessun impatto sui servizi.",
    daysAgo: 38,
    start: "09:00",
    end: "10:30",
    executorIds: ["ppl-andrea"],
  },
  {
    id: "bastion",
    projectId: "prj-tributi",
    categoryId: "cat-tributi-infra",
    title: "Patch kernel sul bastion host",
    description: "Aggiornamento di sicurezza del kernel e riavvio programmato.",
    outcome: "fallita",
    closingNote:
      "Il pacchetto dell'agent di monitoraggio blocca l'upgrade. Da rifare dopo l'aggiornamento dell'agent.",
    daysAgo: 30,
    start: "18:00",
    end: "19:00",
    executorIds: ["ppl-netops"],
    slotNote: "Finestra serale concordata",
  },
  {
    id: "bastion-retry",
    projectId: "prj-tributi",
    categoryId: "cat-tributi-infra",
    title: "Patch kernel sul bastion host (secondo tentativo)",
    description: "Nuovo tentativo dopo l'aggiornamento dell'agent CloudWatch.",
    outcome: "fatto",
    closingNote: "Patch applicata, riavvio in 4 minuti. Accessi SSH verificati.",
    daysAgo: 23,
    start: "18:00",
    end: "18:45",
    executorIds: ["ppl-netops"],
  },
  {
    id: "restore",
    projectId: "prj-tributi",
    categoryId: "cat-tributi-app",
    title: "Restore di prova da snapshot RDS",
    description: "Verifica trimestrale del piano di disaster recovery.",
    outcome: "fatto",
    closingNote: "Restore completato in 22 minuti, dati coerenti. Report in Drive.",
    daysAgo: 16,
    start: "14:00",
    end: "16:00",
    executorIds: ["ppl-laura"],
  },
  {
    id: "ami",
    projectId: "prj-tributi",
    categoryId: "cat-tributi-app",
    title: "Aggiornamento AMI degli application server",
    description: "Rilascio della nuova AMI con Java 21 sull'auto scaling group.",
    outcome: "fallita",
    closingNote:
      "Health check falliti sulla nuova AMI, rollback eseguito. Manca un parametro JVM nel launch template.",
    daysAgo: 9,
    start: "21:00",
    end: "22:30",
    executorIds: ["ppl-andrea", "ppl-marco"],
  },
  {
    id: "ente-a",
    projectId: "prj-azure-comuni",
    categoryId: "cat-azure-app",
    title: "Migrazione Comune di Cesena",
    description: "Lift-and-shift delle VM applicative e del database.",
    outcome: "fatto",
    closingNote: "Migrazione andata a buon fine. Collaudo del referente superato.",
    daysAgo: 35,
    start: "10:00",
    end: "11:00",
    executorIds: ["ppl-team-azure", "ppl-referente-it"],
  },
  {
    id: "ente-b",
    projectId: "prj-azure-comuni",
    categoryId: "cat-azure-app",
    title: "Migrazione Comune di Forlì",
    description: "Lift-and-shift delle VM applicative e del database.",
    outcome: "fallita",
    closingNote:
      "Problema relativo alle librerie sovrapposte: due versioni di OpenSSL sulla VM migrata.",
    daysAgo: 26,
    start: "15:00",
    end: "16:00",
    executorIds: ["ppl-team-azure"],
  },
  {
    id: "ente-b-retry",
    projectId: "prj-azure-comuni",
    categoryId: "cat-azure-app",
    title: "Migrazione Comune di Forlì (secondo tentativo)",
    description: "Nuovo tentativo con immagine ripulita dalle librerie duplicate.",
    outcome: "fatto",
    closingNote: "Migrazione completata. Librerie allineate, servizi avviati al primo colpo.",
    daysAgo: 19,
    start: "15:00",
    end: "16:30",
    executorIds: ["ppl-team-azure", "ppl-referente-it"],
  },
  {
    id: "adconnect",
    projectId: "prj-azure-comuni",
    categoryId: "cat-azure-infra",
    title: "Configurazione sync Azure AD Connect",
    description: "Sincronizzazione delle utenze del dominio del Comune pilota.",
    outcome: "fatto",
    closingNote: "Sync attiva ogni 30 minuti, 412 utenze allineate.",
    daysAgo: 12,
    start: "09:30",
    end: "11:00",
    executorIds: ["ppl-sara"],
  },
  {
    id: "ente-c",
    projectId: "prj-azure-comuni",
    categoryId: "cat-azure-app",
    title: "Migrazione Comune di Ravenna",
    description: "Lift-and-shift delle VM applicative e del database.",
    outcome: "fallita",
    closingNote:
      "Replica del database interrotta per timeout VPN. Riprogrammare con il NetOps del cliente.",
    daysAgo: 4,
    start: "10:00",
    end: "12:00",
    executorIds: ["ppl-team-azure"],
    slotNote: "Serve la VPN site-to-site attiva",
  },
  {
    id: "qa-creds",
    projectId: "prj-qa",
    categoryId: "cat-qa-infra",
    title: "Reset credenziali account di servizio QA",
    description: "Rotazione delle password dopo l'uscita di un fornitore.",
    outcome: "fatto",
    closingNote: "Credenziali ruotate e salvate in Secrets Manager. Pipeline verdi.",
    daysAgo: 21,
    start: "11:00",
    end: "11:30",
    executorIds: ["ppl-iam"],
    requesterId: "ppl-helpdesk",
  },
  {
    id: "qa-collaudo",
    projectId: "prj-qa",
    categoryId: "cat-qa-app",
    title: "Collaudo release 4.2 in ambiente QA",
    description: "Smoke test e collaudo funzionale prima del rilascio.",
    outcome: "fallita",
    closingNote: "Collaudo sospeso: dati di test non anonimizzati. Rimandato alla prossima sprint.",
    daysAgo: 7,
    start: "14:30",
    end: "17:00",
    executorIds: ["ppl-giulia"],
    requesterId: "ppl-giulia",
  },
]

for (const execution of executions) {
  const day = addDaysISO(-execution.daysAgo)
  activities.push({
    id: `act-log-${execution.id}`,
    title: execution.title,
    description: execution.description,
    projectId: execution.projectId,
    source: "altro",
    requesterId: execution.requesterId ?? "ppl-tu",
    responsibleId: execution.responsibleId ?? "ppl-tu",
    status: execution.outcome,
    priority: "media",
    waitingOnPersonId: null,
    waitingReason: "",
    closingNote: execution.closingNote,
    attachments: [],
    driveUrl: "",
    categoryId: execution.categoryId,
    createdAt: created,
    updatedAt: created,
  })
  tasks.push({
    id: `tsk-log-${execution.id}`,
    activityId: `act-log-${execution.id}`,
    startsAt: `${day}T${execution.start}`,
    endsAt: execution.end ? `${day}T${execution.end}` : null,
    executorIds: execution.executorIds ?? [],
    notes: execution.slotNote ?? "",
  })
}

export const EMPTY_STORE: NimbusStore = {
  version: 6,
  people: [],
  projects: [],
  activities: [],
  tasks: [],
}

export const DEMO_STORE: NimbusStore = {
  version: 6,
  people,
  projects,
  activities: activities.map(completeActivity),
  tasks,
}
