import { addDaysISO, nowISO } from "@/lib/dates"
import type { Activity, NimbusStore, Project } from "@/lib/types"

const created = nowISO()

const projects: Project[] = [
  {
    id: "prj-tributi",
    name: "Cloud AWS · Piattaforma Tributi",
    client: "Maggioli — Area Enti Locali",
    status: "attivo",
    driveUrl: "https://drive.google.com/drive/folders/tributi-cloud",
    people: "Andrea Rossi (dev), Laura Conti (funzionale), NetOps",
    notes:
      "Ambienti prod/QA su AWS. Priorità: certificati, peering VPC e finestre di manutenzione concordate con il cliente.",
    createdAt: created,
    updatedAt: created,
  },
  {
    id: "prj-azure-comuni",
    name: "Migrazione Azure · Comuni",
    client: "Maggioli — Cloud Practice",
    status: "attivo",
    driveUrl: "https://drive.google.com/drive/folders/migrazione-azure-comuni",
    people: "Sara Greco (architettura), team Azure, referente cliente",
    notes:
      "Lift-and-shift di tre comuni pilota. Kick-off già fatto; manca la finestra AD e il piano RDS.",
    createdAt: created,
    updatedAt: created,
  },
  {
    id: "prj-qa",
    name: "Supporto ambienti QA",
    client: "Maggioli — Internal IT",
    status: "in_attesa",
    driveUrl: "https://drive.google.com/drive/folders/ambienti-qa",
    people: "Helpdesk interno, team IAM",
    notes:
      "Richieste spot di accessi e collaudi. Tenerle in inbox e smistarle senza aprire un nuovo progetto ogni volta.",
    createdAt: created,
    updatedAt: created,
  },
]

const activities: Activity[] = [
  {
    id: "act-inbox-rimini",
    title: "Nuovo ambiente di collaudo per il Comune di Rimini",
    description:
      "Email del commerciale: serve un ambiente QA isolato entro la prossima sprint. Verificare se rientra in Tributi o in un progetto a parte.",
    projectId: null,
    source: "email",
    requester: "Paolo Mancini (commerciale)",
    type: "eseguo",
    status: "inbox",
    priority: "alta",
    dueDate: null,
    waitingOn: "",
    waitingReason: "",
    driveUrl: "",
    createdAt: created,
    updatedAt: created,
  },
  {
    id: "act-inbox-iam",
    title: "Accessi IAM al bucket backup-dev",
    description:
      "Messaggio Teams: tre sviluppatori non vedono gli oggetti del bucket. Probabile policy errata sul ruolo di QA.",
    projectId: "prj-qa",
    source: "chat",
    requester: "Giulia Ferri (dev)",
    type: "eseguo",
    status: "inbox",
    priority: "media",
    dueDate: null,
    waitingOn: "",
    waitingReason: "",
    driveUrl: "",
    createdAt: created,
    updatedAt: created,
  },
  {
    id: "act-overdue-tls",
    title: "Rinnovo certificato TLS sul load balancer di produzione",
    description:
      "Scadenza ACM già superata nel calendario. Coordinare il cut-over con il funzionale e aggiornare la cartella Drive dei certificati.",
    projectId: "prj-tributi",
    source: "altro",
    requester: "Monitoraggio CloudWatch",
    type: "eseguo",
    status: "in_corso",
    priority: "alta",
    dueDate: addDaysISO(-2),
    waitingOn: "",
    waitingReason: "",
    driveUrl: "https://drive.google.com/drive/folders/tributi-certificati",
    createdAt: created,
    updatedAt: created,
  },
  {
    id: "act-today-peering",
    title: "Allineamento team rete sul peering VPC di QA",
    description:
      "Serve conferma CIDR e route table prima di aprire il ticket AWS. Tu coordini, non esegui il change.",
    projectId: "prj-tributi",
    source: "chat",
    requester: "Laura Conti",
    type: "coordino",
    status: "in_corso",
    priority: "alta",
    dueDate: addDaysISO(0),
    waitingOn: "NetOps",
    waitingReason: "Manca il CIDR definitivo del VPC QA",
    driveUrl: "",
    createdAt: created,
    updatedAt: created,
  },
  {
    id: "act-rds",
    title: "Stima effort migrazione RDS PostgreSQL 16",
    description:
      "Preparare una stima per il steering committee: downtime, replica, rollback. Documento da lasciare in Drive.",
    projectId: "prj-azure-comuni",
    source: "email",
    requester: "Sara Greco",
    type: "eseguo",
    status: "in_corso",
    priority: "media",
    dueDate: addDaysISO(2),
    waitingOn: "",
    waitingReason: "",
    driveUrl: "",
    createdAt: created,
    updatedAt: created,
  },
  {
    id: "act-wait-firewall",
    title: "Apertura firewall verso SFTP Maggioli",
    description:
      "I collaudi del Comune pilota sono bloccati. Sollecitare NetOps se non arriva risposta oggi.",
    projectId: "prj-tributi",
    source: "email",
    requester: "Andrea Rossi",
    type: "coordino",
    status: "in_attesa",
    priority: "alta",
    dueDate: addDaysISO(-1),
    waitingOn: "Marco Bianchi (NetOps)",
    waitingReason: "Change firewall in coda CAB",
    driveUrl: "",
    createdAt: created,
    updatedAt: created,
  },
  {
    id: "act-wait-ad",
    title: "Conferma finestra di manutenzione Azure AD",
    description:
      "Senza la finestra del cliente non si parte con i tre comuni pilota.",
    projectId: "prj-azure-comuni",
    source: "email",
    requester: "Referente cliente",
    type: "coordino",
    status: "in_attesa",
    priority: "media",
    dueDate: addDaysISO(1),
    waitingOn: "Referente IT cliente",
    waitingReason: "Attesa conferma calendario interno",
    driveUrl: "",
    createdAt: created,
    updatedAt: created,
  },
  {
    id: "act-kickoff",
    title: "Redigere verbale kick-off migrazione Azure",
    description:
      "Trascrivere decisioni, rischi e prossimi passi. Caricare il verbale in Drive e spedirlo ai presenti.",
    projectId: "prj-azure-comuni",
    source: "altro",
    requester: "Tu",
    type: "eseguo",
    status: "in_corso",
    priority: "bassa",
    dueDate: addDaysISO(1),
    waitingOn: "",
    waitingReason: "",
    driveUrl: "https://drive.google.com/drive/folders/migrazione-azure-comuni",
    createdAt: created,
    updatedAt: created,
  },
  {
    id: "act-done-eip",
    title: "Ticket AWS Support per quota Elastic IP",
    description: "Quota alzata. Ticket chiuso, nota lasciata in Drive.",
    projectId: "prj-tributi",
    source: "altro",
    requester: "Tu",
    type: "eseguo",
    status: "fatto",
    priority: "media",
    dueDate: addDaysISO(-5),
    waitingOn: "",
    waitingReason: "",
    driveUrl: "",
    createdAt: created,
    updatedAt: created,
  },
]

export const SEED_STORE: NimbusStore = {
  version: 1,
  projects,
  activities,
}
